version: "2"

services:
  web:
    build: .
    # build from Dockerfile
    context: ./Path
    dockerfile: Dockerfile
    ports:
      - "8000:6379"
    volumes:
      - .:/code
  redis:
    image: redis
    ports:
      - "8000:6379"
